#include "stdafx.h"
#include "MainFrm.h"
#include "LampaBridge.h"
#include "Version.h"

CLampaBridge& CLampaBridge::Instance() { static CLampaBridge s; return s; }
void CLampaBridge::AddCors(CStringA& hdr) const { hdr += "Access-Control-Allow-Origin: *\r\nAccess-Control-Allow-Methods: GET, POST, OPTIONS\r\nAccess-Control-Allow-Headers: Content-Type\r\n"; }
bool CLampaBridge::IsLampaPath(const CString& path) const { return path.Left(7).CompareNoCase(L"/lampa/")==0; }
bool CLampaBridge::IsBridgePath(const CString& path) const { return path.CompareNoCase(L"/ping")==0 || path.CompareNoCase(L"/state")==0 || path.CompareNoCase(L"/events")==0 || IsLampaPath(path); }

int64_t CLampaBridge::NowMs() const { return (int64_t)GetTickCount64(); }
int64_t CLampaBridge::PositionMs(CMainFrame* f) const { return f ? (int64_t)(f->GetPos()/10000) : 0; }
int64_t CLampaBridge::DurationMs(CMainFrame* f) const { return f ? (int64_t)(f->GetDur()/10000) : 0; }
bool CLampaBridge::CheckToken(const CString& token) const { return m_session.localToken.IsEmpty() || token == m_session.localToken; }

void CLampaBridge::EmitEvent(const CStringA& type, const CStringA& payloadJson, bool asState){
	LampaBridgeEnvelope e; e.schema=m_session.schemaVersion; e.type=type; e.client=UTF8(m_session.client); e.sessionId=UTF8(m_session.sessionId); e.ts=NowMs(); e.payloadJson=payloadJson;
	m_session.store.events.push_back(e); while (m_session.store.events.size()>200) m_session.store.events.pop_front();
	if (asState) { m_session.store.lastState=e; m_session.store.hasLastState=true; }
}
void CLampaBridge::EmitSessionStarted(CMainFrame*){ EmitEvent("SessionStarted", "{\"mode\":\""+UTF8(m_session.bridgeMode)+"\"}"); }
void CLampaBridge::EmitPlaybackStateChanged(CMainFrame* f){
	OAFilterState fs=f?f->GetMediaState():State_Stopped; CStringA st="stopped"; if(fs==State_Running) st="playing"; else if(fs==State_Paused) st="paused"; EmitEvent("PlaybackStateChanged", "{\"state\":\""+st+"\"}");
}
void CLampaBridge::EmitPositionTick(CMainFrame* f, bool force){ if(!m_session.emitPosition && !force) return; int64_t now=NowMs(); if(!force && now-m_session.lastPositionEventTs<m_session.positionIntervalMs) return; m_session.lastPositionEventTs=now; CStringA p; p.Format("{\"positionMs\":%lld,\"durationMs\":%lld}", PositionMs(f), DurationMs(f)); EmitEvent("PositionTick", p, false); }
void CLampaBridge::EmitSeekCompleted(int64_t fromMs, int64_t toMs){ CStringA p; p.Format("{\"fromMs\":%lld,\"toMs\":%lld}", fromMs, toMs); EmitEvent("SeekCompleted", p); }
void CLampaBridge::EmitPlaylistItemChanged(CMainFrame*, const CStringA& reason){ EmitEvent("PlaylistItemChanged", "{\"reason\":\""+reason+"\",\"activeIndex\":"+CStringA(std::to_string(m_session.activeIndex).c_str())+"}"); }
void CLampaBridge::EmitPlaybackEnded(CMainFrame*){ EmitEvent("PlaybackEnded", "{}", false); }
void CLampaBridge::EmitSessionFinished(CMainFrame*, const CStringA& endBy){ EmitEvent("SessionFinished", "{\"endBy\":\""+endBy+"\"}"); }
void CLampaBridge::EmitError(const CStringA& code, const CStringA& message){ EmitEvent("Error", "{\"code\":\""+code+"\",\"message\":\""+message+"\"}", false); }

bool CLampaBridge::Health(CStringA& body) const { body = "{\"ok\":true,\"name\":\"MPC-Lampa-bridge\",\"player\":\"MPC-BE\",\"version\":\"" + CStringA(MPC_VERSION_FULL_STR) + "\"}"; return true; }
bool CLampaBridge::Ping(CStringA& body) const { body = "{\"ok\":true}"; return true; }
bool CLampaBridge::State(const CString& sid, const CString& token, CMainFrame* pMainFrame, CStringA& body){ EmitPositionTick(pMainFrame, false); if (sid != m_session.sessionId || !CheckToken(token)) { body = "{\"error\":\"forbidden\"}"; return true; } body = LampaBridgeJson::BuildStateResponse(m_session.store.hasLastState ? &m_session.store.lastState : nullptr); return true; }
bool CLampaBridge::Events(const CString& sid, const CString& token, int limit, CStringA& body){ if (sid != m_session.sessionId || !CheckToken(token)) { body = "{\"error\":\"forbidden\"}"; return true; } if(limit<=0) limit=50; if(limit>200) limit=200; body = LampaBridgeJson::BuildEventsResponse(m_session.store.events, limit); return true; }

bool CLampaBridge::OpenIndex(CMainFrame* pMainFrame, int index){ if(!pMainFrame||index<0||index>=(int)m_session.items.size()) return false; auto& it=m_session.items[index]; std::list<CString> cmdln; cmdln.emplace_back(it.url); int len=0; for(auto&s:cmdln){len+=(s.GetLength()+1)*sizeof(WCHAR);} std::unique_ptr<BYTE[]> buff(new BYTE[4+len]); BYTE* p=buff.get(); *(DWORD*)p=cmdln.size(); p+=4; for(auto&s:cmdln){int l=(s.GetLength()+1)*sizeof(WCHAR); memcpy(p,(LPCWSTR)s,l); p+=l;} COPYDATASTRUCT cds{0x6ABE51,(DWORD)(p-buff.get()),buff.get()}; pMainFrame->SendMessageW(WM_COPYDATA,0,(LPARAM)&cds); m_session.activeIndex=index; m_session.activeUrl=it.url; m_session.activeTitle=it.title; m_session.activeTimelineHash=it.timelineHash; m_session.requestedPosition=it.position; return true; }

bool CLampaBridge::Open(CMainFrame* pMainFrame, const CStringA& payloadBody, CStringA& body){ LampaOpenPayload p; CString err; if(!LampaBridgeJson::ParseOpenPayload(payloadBody,p,err)){ body="{\"ok\":false,\"error\":\""+LampaBridgeJson::EscapeJson(err)+"\"}"; return true; } m_session.Clear(); if(!p.bridgeSessionId.IsEmpty()) m_session.sessionId=p.bridgeSessionId; else m_session.sessionId.Format(L"%08x", GetTickCount()); m_session.client = p.bridgeClient.IsEmpty()?L"lampa":p.bridgeClient; if(!p.bridgeMode.IsEmpty()) m_session.bridgeMode=p.bridgeMode; m_session.localToken=p.bridgeLocalToken; m_session.emitPosition=p.bridgeEmitPosition; m_session.positionIntervalMs=p.bridgePositionIntervalMs; m_session.schemaVersion=p.bridgeSchemaVersion; m_session.timelineDuration=p.timelineDuration; m_session.timelinePercent=p.timelinePercent; if(p.playlist.empty()){ LampaBridgePlaylistItem i; i.url=p.url; i.title=p.title; i.position=p.position; i.timelineHash=p.timelineHash; m_session.items.push_back(i);} else m_session.items=p.playlist; int active=0; for(size_t i=0;i<m_session.items.size();i++) if(m_session.items[i].url==p.url){active=(int)i;break;} if(!OpenIndex(pMainFrame, active)){ body="{\"ok\":false,\"error\":\"open failed\"}"; return true;} if(m_session.requestedPosition<=10 && p.timelineTime>10) m_session.requestedPosition=p.timelineTime; ApplyPendingSeek(pMainFrame); EmitSessionStarted(pMainFrame); EmitPlaybackStateChanged(pMainFrame); EmitPositionTick(pMainFrame, true); body.Format("{\"ok\":true,\"session_id\":\"%s\",\"active_index\":%d,\"title\":\"%s\"}", LampaBridgeJson::EscapeJson(m_session.sessionId), m_session.activeIndex, LampaBridgeJson::EscapeJson(m_session.activeTitle)); return true; }

void CLampaBridge::ApplyPendingSeek(CMainFrame* pMainFrame){ if(!pMainFrame||m_session.requestedPosition<=10) return; OAFilterState fs=pMainFrame->GetMediaState(); double dur=(double)pMainFrame->GetDur()/10000000.0; if(fs==State_Stopped||dur<=0.0) return; if(m_session.timelinePercent>=90){ m_session.requestedPosition=-1.0; return; } double pos=m_session.requestedPosition; if(pos>dur-15.0) pos=dur-15.0; if(pos>1.0){ pMainFrame->SeekTo((REFERENCE_TIME)(pos*10000000.0)); } m_session.requestedPosition=-1.0; }

void CLampaBridge::FillStatus(CMainFrame* pMainFrame, CStringA& body){ OAFilterState fs = pMainFrame ? pMainFrame->GetMediaState() : State_Stopped; const char* state="unknown"; if(fs==State_Running) state="playing"; else if(fs==State_Paused) state="paused"; else if(fs==State_Stopped) state="stopped"; double t=pMainFrame?(double)pMainFrame->GetPos()/10000000.0:0; double d=pMainFrame?(double)pMainFrame->GetDur()/10000000.0:0; int percent=(d>0)?(int)(t*100.0/d):0; if(!m_session.HasActive()){ body="{\"ok\":true,\"opened\":false,\"state\":\"stopped\",\"time\":0,\"duration\":0,\"percent\":0,\"active_index\":-1,\"title\":\"\",\"url\":\"\",\"timeline_hash\":\"\"}"; return;} body.Format("{\"ok\":true,\"opened\":true,\"state\":\"%s\",\"time\":%.3f,\"duration\":%.3f,\"percent\":%d,\"active_index\":%d,\"title\":\"%s\",\"url\":\"%s\",\"timeline_hash\":\"%s\"}", state,t,d,percent,m_session.activeIndex,LampaBridgeJson::EscapeJson(m_session.activeTitle),LampaBridgeJson::EscapeJson(m_session.activeUrl),LampaBridgeJson::EscapeJson(m_session.activeTimelineHash)); }
bool CLampaBridge::Status(CMainFrame* pMainFrame, CStringA& body){ ApplyPendingSeek(pMainFrame); EmitPositionTick(pMainFrame, false); FillStatus(pMainFrame, body); return true; }

bool CLampaBridge::Command(CMainFrame* pMainFrame, const CStringA& payloadBody, CStringA& body){ rapidjson::Document d; if(d.Parse(payloadBody).HasParseError()||!d.IsObject()){ body="{\"ok\":false,\"error\":\"invalid json\"}"; return true;} CStringA cmd; getJsonValue(d,"command",cmd); cmd.MakeLower(); if(cmd=="play"){ pMainFrame->SendMessageW(WM_COMMAND,ID_PLAY_PLAY); EmitPlaybackStateChanged(pMainFrame);} else if(cmd=="pause"){ pMainFrame->SendMessageW(WM_COMMAND,ID_PLAY_PAUSE); EmitPlaybackStateChanged(pMainFrame);} else if(cmd=="stop"){ pMainFrame->SendMessageW(WM_COMMAND,ID_PLAY_STOP); EmitPlaybackStateChanged(pMainFrame); EmitPlaybackEnded(pMainFrame);} else if(cmd=="seek"){ double tm=0; if(d.HasMember("time")&&d["time"].IsNumber()) tm=d["time"].GetDouble(); int64_t from=PositionMs(pMainFrame); pMainFrame->SeekTo((REFERENCE_TIME)(tm*10000000.0)); EmitSeekCompleted(from, (int64_t)(tm*1000.0)); EmitPositionTick(pMainFrame, true);} else if(cmd=="next"&&m_session.activeIndex+1<(int)m_session.items.size()){ OpenIndex(pMainFrame,m_session.activeIndex+1); ApplyPendingSeek(pMainFrame); EmitPlaylistItemChanged(pMainFrame, "next"); EmitPlaybackStateChanged(pMainFrame); EmitPositionTick(pMainFrame, true);} else if(cmd=="prev"&&m_session.activeIndex>0){ OpenIndex(pMainFrame,m_session.activeIndex-1); ApplyPendingSeek(pMainFrame); EmitPlaylistItemChanged(pMainFrame, "prev"); EmitPlaybackStateChanged(pMainFrame); EmitPositionTick(pMainFrame, true);} FillStatus(pMainFrame, body); return true; }

bool CLampaBridge::Close(CMainFrame* pMainFrame, CStringA& body){ EmitSessionFinished(pMainFrame, "user"); if(pMainFrame) pMainFrame->SendMessageW(WM_COMMAND,ID_PLAY_STOP); m_session.items.clear(); m_session.activeIndex=0; m_session.activeUrl.Empty(); m_session.activeTitle.Empty(); m_session.activeTimelineHash.Empty(); body="{\"ok\":true}"; return true; }
