#include "stdafx.h"
#include "MainFrm.h"
#include "LampaBridge.h"
#include "Version.h"

CLampaBridge& CLampaBridge::Instance() { static CLampaBridge s; return s; }
void CLampaBridge::AddCors(CStringA& hdr) const { hdr += "Access-Control-Allow-Origin: *\r\nAccess-Control-Allow-Methods: GET, POST, OPTIONS\r\nAccess-Control-Allow-Headers: Content-Type\r\n"; }
bool CLampaBridge::IsLampaPath(const CString& path) const { return path.Left(7).CompareNoCase(L"/lampa/")==0; }

bool CLampaBridge::Health(CStringA& body) const { body = "{\"ok\":true,\"name\":\"MPC-Lampa-bridge\",\"player\":\"MPC-BE\",\"version\":\"" + CStringA(MPC_VERSION_FULL_STR) + "\"}"; return true; }

bool CLampaBridge::OpenIndex(CMainFrame* pMainFrame, int index){ if(!pMainFrame||index<0||index>=(int)m_session.items.size()) return false; auto& it=m_session.items[index]; std::list<CString> cmdln; cmdln.emplace_back(it.url); int len=0; for(auto&s:cmdln){len+=(s.GetLength()+1)*sizeof(WCHAR);} std::unique_ptr<BYTE[]> buff(new BYTE[4+len]); BYTE* p=buff.get(); *(DWORD*)p=cmdln.size(); p+=4; for(auto&s:cmdln){int l=(s.GetLength()+1)*sizeof(WCHAR); memcpy(p,(LPCWSTR)s,l); p+=l;} COPYDATASTRUCT cds{0x6ABE51,(DWORD)(p-buff.get()),buff.get()}; pMainFrame->SendMessageW(WM_COPYDATA,0,(LPARAM)&cds); m_session.activeIndex=index; m_session.activeUrl=it.url; m_session.activeTitle=it.title; m_session.activeTimelineHash=it.timelineHash; m_session.requestedPosition=it.position; return true; }

bool CLampaBridge::Open(CMainFrame* pMainFrame, const CStringA& payloadBody, CStringA& body){ LampaOpenPayload p; CString err; if(!LampaBridgeJson::ParseOpenPayload(payloadBody,p,err)){ body="{\"ok\":false,\"error\":\""+LampaBridgeJson::EscapeJson(err)+"\"}"; DLog(L"Lampa open parse error: %s", err.GetString()); return true; } m_session.Clear(); m_session.sessionId.Format(L"%08x", GetTickCount()); m_session.timelineDuration=p.timelineDuration; m_session.timelinePercent=p.timelinePercent; if(p.playlist.empty()){ LampaBridgePlaylistItem i; i.url=p.url; i.title=p.title; i.position=p.position; i.timelineHash=p.timelineHash; m_session.items.push_back(i);} else m_session.items=p.playlist; int active=0; for(size_t i=0;i<m_session.items.size();i++) if(m_session.items[i].url==p.url){active=(int)i;break;} DLog(L"Lampa open playlist=%u active=%d", (unsigned)m_session.items.size(), active); if(!OpenIndex(pMainFrame, active)){ body="{\"ok\":false,\"error\":\"open failed\"}"; return true;} if(m_session.requestedPosition<=10 && p.timelineTime>10) m_session.requestedPosition=p.timelineTime; ApplyPendingSeek(pMainFrame); body.Format("{\"ok\":true,\"session_id\":\"%s\",\"active_index\":%d,\"title\":\"%s\"}", LampaBridgeJson::EscapeJson(m_session.sessionId), m_session.activeIndex, LampaBridgeJson::EscapeJson(m_session.activeTitle)); return true; }

void CLampaBridge::ApplyPendingSeek(CMainFrame* pMainFrame){ if(!pMainFrame||m_session.requestedPosition<=10) return; OAFilterState fs=pMainFrame->GetMediaState(); double dur=(double)pMainFrame->GetDur()/10000000.0; if(fs==State_Stopped||dur<=0.0) return; if(m_session.timelinePercent>=90){ m_session.requestedPosition=-1.0; return; } double pos=m_session.requestedPosition; if(pos>dur-15.0) pos=dur-15.0; if(pos>1.0){ pMainFrame->SeekTo((REFERENCE_TIME)(pos*10000000.0)); DLog(L"Lampa seek to %.3f", pos);} m_session.requestedPosition=-1.0; }

void CLampaBridge::FillStatus(CMainFrame* pMainFrame, CStringA& body){ OAFilterState fs = pMainFrame ? pMainFrame->GetMediaState() : State_Stopped; const char* state="unknown"; if(fs==State_Running) state="playing"; else if(fs==State_Paused) state="paused"; else if(fs==State_Stopped) state="stopped"; double t=pMainFrame?(double)pMainFrame->GetPos()/10000000.0:0; double d=pMainFrame?(double)pMainFrame->GetDur()/10000000.0:0; int percent=(d>0)?(int)(t*100.0/d):0; if(!m_session.HasActive()){ body="{\"ok\":true,\"opened\":false,\"state\":\"stopped\",\"time\":0,\"duration\":0,\"percent\":0,\"active_index\":-1,\"title\":\"\",\"url\":\"\",\"timeline_hash\":\"\"}"; return;} body.Format("{\"ok\":true,\"opened\":true,\"state\":\"%s\",\"time\":%.3f,\"duration\":%.3f,\"percent\":%d,\"active_index\":%d,\"title\":\"%s\",\"url\":\"%s\",\"timeline_hash\":\"%s\"}", state,t,d,percent,m_session.activeIndex,LampaBridgeJson::EscapeJson(m_session.activeTitle),LampaBridgeJson::EscapeJson(m_session.activeUrl),LampaBridgeJson::EscapeJson(m_session.activeTimelineHash)); }
bool CLampaBridge::Status(CMainFrame* pMainFrame, CStringA& body){ ApplyPendingSeek(pMainFrame); FillStatus(pMainFrame, body); return true; }

bool CLampaBridge::Command(CMainFrame* pMainFrame, const CStringA& payloadBody, CStringA& body){ rapidjson::Document d; if(d.Parse(payloadBody).HasParseError()||!d.IsObject()){ body="{\"ok\":false,\"error\":\"invalid json\"}"; return true;} CStringA cmd; getJsonValue(d,"command",cmd); cmd.MakeLower(); if(cmd=="play") pMainFrame->SendMessageW(WM_COMMAND,ID_PLAY_PLAY); else if(cmd=="pause") pMainFrame->SendMessageW(WM_COMMAND,ID_PLAY_PAUSE); else if(cmd=="stop") pMainFrame->SendMessageW(WM_COMMAND,ID_PLAY_STOP); else if(cmd=="seek"){ double tm=0; if(d.HasMember("time")&&d["time"].IsNumber()) tm=d["time"].GetDouble(); pMainFrame->SeekTo((REFERENCE_TIME)(tm*10000000.0)); DLog(L"Lampa command seek %.3f", tm);} else if(cmd=="next"&&m_session.activeIndex+1<(int)m_session.items.size()){ OpenIndex(pMainFrame,m_session.activeIndex+1); ApplyPendingSeek(pMainFrame);} else if(cmd=="prev"&&m_session.activeIndex>0){ OpenIndex(pMainFrame,m_session.activeIndex-1); ApplyPendingSeek(pMainFrame);} FillStatus(pMainFrame, body); return true; }

bool CLampaBridge::Close(CMainFrame* pMainFrame, CStringA& body){ if(pMainFrame) pMainFrame->SendMessageW(WM_COMMAND,ID_PLAY_STOP); m_session.Clear(); body="{\"ok\":true}"; return true; }
